[pytest]
markers =
    slow: marks tests as slow (opt-out with '-m "not slow"')
    network: marks tests as requiring internet connectivity
    dl: marks tests as requiring a download to the filesystem of some kind (opt-out with '-m "not dl"')
    huge_dl: marks tests as requiring an enormous download (opt-in with '--run-huge-dl')
