[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    huge_dl: marks tests as requiring an enormous download (opt-in with '--run-huge-dl')
    network: marks tests as requiring internet connectivity