version: '3.8'

services:
  web:
    image: ghcr.io/wowwood/slurp:latest
    command: web
    environment:
      SLURP_REDIS_URL: "redis://redis:6379"
    volumes:
      - /tmp/slurp_data:/data
      - ../../config.toml:/app/config.toml
    ports:
      - "5010:8000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  celery_worker:
    image: ghcr.io/wowwood/slurp:latest
    command: celery worker -Q celery,fetch
    environment:
      SLURP_REDIS_URL: "redis://redis:6379"
    volumes:
      - /tmp/slurp_data:/data
      - ../../config.toml:/app/config.toml
    depends_on:
      - redis

  celery_beat:
    image: ghcr.io/wowwood/slurp:latest
    command: celery beat
    environment:
      SLURP_REDIS_URL: "redis://redis:6379"
    volumes:
      - /tmp/slurp_data:/data
      - ../../config.toml:/app/config.toml
    depends_on:
      - redis

  flower:
    image: ghcr.io/wowwood/slurp:latest
    command: celery flower
    environment:
      SLURP_REDIS_URL: "redis://redis:6379"
    volumes:
      - /tmp/slurp_data:/data
      - ../../config.toml:/app/config.toml
    ports:
      - "5555:5555"
    depends_on:
      - redis

  cobalt:
    image: ghcr.io/imputnet/cobalt:11

    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt

    ports:
      - "9090:9000/tcp"
      # if you use a reverse proxy (such as nginx),
      # uncomment the next line and remove the one above (9000:9000/tcp):
      # - 127.0.0.1:9000:9000

    environment:
      # replace https://api.url.example/ with your instance's url
      # or else tunneling functionality won't work properly
      API_URL: "http://127.0.0.1:9090/"